name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Push backend folder to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # Clone Hugging Face repo
          git clone https://AbhijeetAnand30:${HF_TOKEN}@huggingface.co/spaces/AbhijeetAnand30/excelina-backend hf_space

          # Sync only the backend folder, excluding the .git directory
          rsync -av --delete --exclude='.git/' backend/ hf_space/

          cd hf_space

          git add .
          git commit -m "CI: Sync from GitHub backend folder" || echo "No changes to commit"

          # Pull to avoid non-fast-forward push errors
          git pull --rebase origin main

          # Push to Hugging Face repo
          git push https://AbhijeetAnand30:${HF_TOKEN}@huggingface.co/spaces/AbhijeetAnand30/excelina-backend main
